name: Maven CI

on:
  push:
    branches:
      - main
      - AnnKathrin
      - Monique
      - Katja
      - maik
  pull_request:
    branches:
      - main
      - AnnKathrin
      - Monique
      - Katja
      - maik

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkt den Code ins Laufverzeichnis aus

      - name: Set up JDK 23
        uses: actions/setup-java@v3  # Rüstet Java auf
        with:
          distribution: 'temurin'  # JDK-Distribution
          java-version: '23'        # Java-Version auf 23 setzen


      - name: Give permissions
        run: chmod +x ./mvnw
        working-directory: backend

      - name: Run tests
        run: mvn test

      - name: Build and test with Maven
        run: ./mvnw clean install  # Führt den Maven-Build aus
        working-directory: backend
