name: Maven CI

on:
  push:
    branches:
      - maik_CICD  # Trigger f端r Push-Events auf den Branch maik_CICD
  pull_request:
    branches:
      - maik_CICD  # Trigger f端r Pull Requests in den Branch maik_CICD

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkt den Code ins Laufverzeichnis aus

      - name: Set up JDK 23
        uses: actions/setup-java@v3  # R端stet Java auf
        with:
          distribution: 'temurin'  # JDK-Distribution
          java-version: '23'        # Java-Version auf 23 setzen


      - name: give permission
        run: chmod +x ./mvnw
        working-directory: backend

      - name: Build with Maven
        run: ./backend/mvnw clean install  # F端hrt den Maven-Build aus

