name: Maven CI

on:
  push:
    branches:
      - main
      - AnnKathrin
      - Monique
      - Katja
      - maik
  pull_request:
    branches:
      - main
      - AnnKathrin
      - Monique
      - Katja
      - maik

jobs:
  buildAndTest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checkt den Code ins Laufverzeichnis aus

      - name: Set up JDK 23
        uses: actions/setup-java@v4  # Rüstet Java auf
        with:
          distribution: 'temurin'  # JDK-Distribution
          java-version: '23'        # Java-Version auf 23 setzen
          cache: maven

      - name: Run tests
        run: mvn test
        working-directory: backend

      - name: Package project
        run: mvn package
        working-directory: backend

      - name: Upload target folder
        uses: actions/upload-artifact@v4
        with:
          name: target
          path: backend/target  # Pfad zum Zielverzeichnis, das hochgeladen werden soll

      - name: Build with Maven
        run: mvn clean install  # Führt den Maven-Build aus
        working-directory: backend

